### ISSUE TITLE
Create a runnable version of the 7 Wonders

### ISSUE THREAD

**Issue by 1r0nm4g3** [Still-River/7-Wonders-ML#1]
- [ ] Create a game class that runs the game
- [ ] Create a player class that allows the player to make actions and stores information about the player
- [x] Create a deck class that contains all the cards
- [x] Create a card class
- [x] Create all the cards as card objects
- [x] Create a hand class that gets passed between players
- [ ] Create a Wonder class and create each Wonder from the game
- [x] Create Resources Class
- [ ] Create Shields Class
- [x] Create Science Class
- [ ] Create Market Class
